#!/usr/bin/env bash

echo "Start"

psql -p $DB_PORT -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$DB_NAME' AND pid <> pg_backend_pid();" $DB_NAME

dropdb -h $DB_HOST -p $DB_PORT -U $DB_USER $DB_NAME    
echo "Drop DB"

createdb -h $DB_HOST -p $DB_PORT -U $DB_USER -O $DB_OWNER $DB_NAME
echo "Create DB"

psql -p $DB_PORT -d $DB_NAME -U $DB_USER -f schema.sql
echo "Schema upload"

echo "Finish"